# Generated by Django 5.0.4 on 2025-11-10 07:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Original announcement text')),
                ('detected_language', models.CharField(default='en', help_text='Auto-detected language code', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(default=5, help_text='Priority level (1-10, higher = more important)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this announcement is currently active')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('email_sent', models.BooleanField(default=False, help_text='Whether email notifications were sent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisplayBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display board name/identifier', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Physical location of the board', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this board is currently active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_boards', to='announcements.announcement')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text='Target language code (hi, ta, te, bn, kn, en)', max_length=10)),
                ('translated_text', models.TextField(help_text='Translated text')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('translation_service', models.CharField(default='libretranslate', help_text='Service used for translation', max_length=50)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='announcements.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text='Language of the audio', max_length=10)),
                ('audio_file', models.FileField(help_text='Generated audio file', upload_to='audio/%Y/%m/%d/')),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duration of audio in seconds', null=True)),
                ('tts_service', models.CharField(default='coqui', help_text='TTS service used (coqui, pyttsx3)', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='announcements.announcement')),
                ('translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='announcements.translation')),
            ],
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', '-created_at'], name='announcemen_status_c8b2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', '-priority', '-created_at'], name='announcemen_is_acti_fa4511_idx'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['announcement', 'language_code'], name='announcemen_announc_dd0b46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('announcement', 'language_code')},
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['announcement', 'language_code'], name='announcemen_announc_852608_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='audiofile',
            unique_together={('announcement', 'language_code')},
        ),
    ]
