# Generated by Django 5.0.4 on 2025-11-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Whether this is an urgent announcement'),
        ),
    ]
