# Generated by Django 5.0.4 on 2025-11-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled time for announcement', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='contact_no',
            field=models.CharField(blank=True, help_text='Contact number', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='handler',
            field=models.CharField(blank=True, help_text='Official name handling this announcement', max_length=100),
        ),
        migrations.AddField(
            model_name='announcement',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the announcement', max_length=200),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, help_text='Announcement title', max_length=200),
        ),
    ]
