# Generated by Django 5.0.4 on 2025-11-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_announcement_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='fixed_at',
            field=models.DateTimeField(blank=True, help_text='When the announcement was marked as fixed', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_fixed',
            field=models.BooleanField(default=False, help_text='Whether this announcement has been fixed/resolved'),
        ),
    ]
